orchestration_task:
  description: |
    Your primary goal is to solve the user's business problem. Analyze the user's request and the statistical summary of their data to create a step-by-step action plan. The plan must be designed to gather all the necessary information to directly answer the user's question.
    The user's request is: {user_prompt}
    The statistical summary is:
    {statistical_summary}

    Your final output must be a clear, numbered list of tasks for your team, written in Brazilian Portuguese.
  expected_output: |
    A numbered list of analysis steps, in Brazilian Portuguese, that will lead to a direct and actionable answer to the user's business problem.
  agent: orchestrator

data_validation_task:
  description: |
    Based on the plan from the orchestrator, execute the necessary Pandas code to validate the primary hypothesis.
    For example, if the hypothesis is that a drop in conversions is linked to a specific campaign's CPC increase,
    write the code to verify this. Any text in your output must be in Brazilian Portuguese.
  expected_output: |
    A JSON object confirming the hypothesis and providing the relevant data, like: `{"hypothesis_confirmed": true, "campaign": "Campaign_X", "cpc_variation": "+50%", "conversion_variation": "-35%"}`. Any text must be in Brazilian Portuguese.
  agent: data_analyst
  context: [orchestration_task]

contextualization_task:
  description: |
    Based on the validated data from the data analyst, provide market context.
    For example, if a CPC increased by 50%, is that normal for the e-commerce sector? Your answer must be in Brazilian Portuguese.
  expected_output: |
    A concise text providing the market context, in Brazilian Portuguese.
  agent: market_context_specialist
  context: [data_validation_task]

synthesis_task:
  description: |
    Synthesize all findings into a final, client-facing report. Your most important job is to directly answer the user's original business problem: **"{user_prompt}"**.
    The report must be clear, actionable, and provide concrete recommendations to help the user achieve their goal. Start the report by restating their goal and immediately address it.
    The report must be written entirely in Brazilian Portuguese.
  expected_output: |
    A final, actionable report in Markdown format, written in Brazilian Portuguese, that directly answers the user's business problem and provides a strategic roadmap.
  agent: synthesis_agent
  context: [data_validation_task, contextualization_task]